name: Lint
on:
	pull_request:
	push:

jobs:
	golangci:
		name: Lint
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v3
			- name: golangci-lint
				uses: golangci/golangci-lint-action@v3
				with:
					args: --issues-exit-code=0
					only-new-issues: true
